[mypy]
python_version = 3.13
strict = True
ignore_missing_imports = True
warn_unused_ignores = True
warn_redundant_casts = True
exclude = build
disallow_any_unimported = True
disallow_any_decorated = True
disallow_any_explicit = True
disallow_any_expr = True
warn_return_any = True

[mypy-curl_cffi.*,httpx.*]
ignore_missing_imports = True
follow_imports = skip
