[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "osint_nexus"
version = "2.0.1"
description = "High-performance OSINT username finder"
dependencies = [
    "httpx",
    "rich",
    "tqdm",
    "aiohttp",
    "pydantic>=2.0.0",
]
requires-python = ">=3.12"

[tool.setuptools]
packages = ["osint_nexus"]

[dependency-groups]
dev = [
    "pytest",
    "pytest-asyncio",
]

[tool.ruff]
line-length = 110

[tool.ruff.lint]
select = ["E", "F", "B", "I"]
