"""Theme constants for UI consistency."""

COLOR_FOUND = "green"
COLOR_NOT_FOUND = "red"
COLOR_HELP = "light_purple"
COLOR_PROGRESS_SUCCESS = "green"
COLOR_PROGRESS_FAILURE = "red"

# Layout Constants
METRICS_BAR_WIDTH = 20
HEADER_HEIGHT = 3
PROGRESS_BAR_HEIGHT = 3
LOG_PANEL_HEIGHT = 8
METRICS_GRAPH_WIDTH = 30
